In [6]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [7]:
df = pd.read_csv("./datasets/iris.csv")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [10]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
X = df[['sepal_length','sepal_width','petal_length','petal_width']]
Y = df['species']

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(X , Y, test_size=0.3)

In [13]:
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

obj = GaussianNB()
obj.fit(X_train,Y_train)
y_pred = obj.predict(X_test)
accuracy = accuracy_score(Y_test,y_pred)
accuracy

0.9333333333333333

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,y_pred)
print(cm)
report = classification_report(Y_test,y_pred)
print(report)


[[13  0  0]
 [ 0 11  2]
 [ 0  1 18]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        13
  versicolor       0.92      0.85      0.88        13
   virginica       0.90      0.95      0.92        19

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45



In [16]:
def calculate_metrics(cm):
    n_classes = cm.shape[0]  # Number of classes
    metrics = {}

    for i in range(n_classes):
        TP = cm[i, i]  # True Positives are on the diagonal
        FP = cm[:, i].sum() - TP  # False Positives (sum of column - diagonal)
        FN = cm[i, :].sum() - TP  # False Negatives (sum of row - diagonal)
        TN = cm.sum() - (TP + FP + FN)  # True Negatives (total sum - TP, FP, FN)
        
        metrics[i] = {'TP': TP, 'TN': TN, 'FP': FP, 'FN': FN}

    return metrics

# Get metrics for each class
metrics = calculate_metrics(cm)

# Print the metrics
for class_index, metric in metrics.items():
    print(f"Class {class_index}:")
    print("TP : " , metric['TP'])
    print(f"  TN: {metric['TN']}")
    print(f"  FP: {metric['FP']}")
    print(f"  FN: {metric['FN']}")
    print()

Class 0:
TP :  13
  TN: 32
  FP: 0
  FN: 0

Class 1:
TP :  11
  TN: 31
  FP: 1
  FN: 2

Class 2:
TP :  18
  TN: 24
  FP: 2
  FN: 1

